In [1]:
#import libraries
import requests
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
r = requests.get('http://swapi.dev/api/')
r.json()

{'people': 'https://swapi.dev/api/people/',
 'planets': 'https://swapi.dev/api/planets/',
 'films': 'https://swapi.dev/api/films/',
 'species': 'https://swapi.dev/api/species/',
 'vehicles': 'https://swapi.dev/api/vehicles/',
 'starships': 'https://swapi.dev/api/starships/'}

Get Full Data of a type (people, planets, vehicles...)

In [3]:
#function to store all the data
def get_full_type_data(base_url):
    data =  requests.get(base_url)
    all_data = []
    data_num = 0
    for i in range(200):
        if data_num < data.json()['count']+1:
            trial=requests.get(base_url+str(i))
            if str(trial) != '<Response [404]>':
                all_data.append(trial.json())
                data_num+=1
    all_data = pd.json_normalize(all_data)
    return all_data

In [4]:
#function to make column numeric
def df_columns_to_numeric(df,columns):
    for column_i in columns:
        unusual_index_list = df.index[df[column_i].str.contains("\D")].tolist()
        # Rule out the unusual charactor in a numeric column
        if len(unusual_index_list)>0:
            df.loc[unusual_index_list,column_i]=np.nan
        df[column_i]=pd.to_numeric(df[column_i])
    return df

PEOPLE

In [5]:
#get and store the people data
people = get_full_type_data('https://swapi.dev/api/people/')

In [6]:
people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/
78,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/
80,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/
81,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/

In [7]:
#return columns name
people.columns

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'gender', 'homeworld', 'films', 'species', 'vehicles',
       'starships', 'created', 'edited', 'url'],
      dtype='object')

In [8]:
# add 3 columns about the number of films , vehicles , starships
people['film_num']=people['films'].apply(lambda x:len(x))
people['vehicles_num']=people['vehicles'].apply(lambda x:len(x))
people['starships_num']=people['starships'].apply(lambda x:len(x))
people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url,film_num,vehicles_num,starships_num
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",2014-12-09T13:50:51.644000Z,2014-12-20T21:17:56.891000Z,https://swapi.dev/api/people/1/,4,2,2
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:10:51.357000Z,2014-12-20T21:17:50.309000Z,https://swapi.dev/api/people/2/,6,0,0
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],2014-12-10T15:11:50.376000Z,2014-12-20T21:17:50.311000Z,https://swapi.dev/api/people/3/,6,0,0
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],2014-12-10T15:18:20.704000Z,2014-12-20T21:17:50.313000Z,https://swapi.dev/api/people/4/,4,0,1
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],2014-12-10T15:20:09.791000Z,2014-12-20T21:17:50.315000Z,https://swapi.dev/api/people/5/,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],2014-12-20T19:43:53.348000Z,2014-12-20T21:17:50.488000Z,https://swapi.dev/api/people/79/,1,1,1
78,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],2014-12-20T19:46:34.209000Z,2014-12-20T21:17:50.491000Z,https://swapi.dev/api/people/80/,1,0,0
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/,2,0,0
80,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/,2,0,0
81,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/,1,0,0

In [9]:
#see the last 3 rows
people.tail(3)

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,created,edited,url,film_num,vehicles_num,starships_num
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],2014-12-20T19:49:35.583000Z,2014-12-20T21:17:50.493000Z,https://swapi.dev/api/people/81/,2,0,0
80,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],2014-12-20T20:18:37.619000Z,2014-12-20T21:17:50.496000Z,https://swapi.dev/api/people/82/,2,0,0
81,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],2014-12-20T20:35:04.260000Z,2014-12-20T21:17:50.498000Z,https://swapi.dev/api/people/83/,1,0,0

In [10]:
#get dataset info
people.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           82 non-null     object
 1   height         82 non-null     object
 2   mass           82 non-null     object
 3   hair_color     82 non-null     object
 4   skin_color     82 non-null     object
 5   eye_color      82 non-null     object
 6   birth_year     82 non-null     object
 7   gender         82 non-null     object
 8   homeworld      82 non-null     object
 9   films          82 non-null     object
 10  species        82 non-null     object
 11  vehicles       82 non-null     object
 12  starships      82 non-null     object
 13  created        82 non-null     object
 14  edited         82 non-null     object
 15  url            82 non-null     object
 16  film_num       82 non-null     int64
 17  vehicles_num   82 non-null     int64
 18  starships_num  82 non-null     int64
dtypes: int64(3), object(16)
memory usage: 12.3+ KB

In [11]:
# change the mass and height columns tybe to numeric type
people = df_columns_to_numeric(people,['height','mass'])

In [12]:
#describe the final data
people.describe()

           height        mass   film_num  vehicles_num  starships_num
count   81.000000   56.000000  82.000000     82.000000      82.000000
mean   174.604938   75.875000   1.975610      0.158537       0.365854
std     34.774157   29.661155   1.305029      0.429456       0.839050
min     66.000000   15.000000   1.000000      0.000000       0.000000
25%    167.000000   55.000000   1.000000      0.000000       0.000000
50%    180.000000   79.000000   1.000000      0.000000       0.000000
75%    191.000000   84.250000   3.000000      0.000000       0.000000
max    264.000000  159.000000   6.000000      2.000000       5.000000

In [13]:
people = people.drop(columns=['created', 'edited'])

In [14]:
# Find the greatest mass and the name og who has it
print(people.iloc[people['mass'].idxmax()]['name'],people['mass'].max())

Grievous 159.0

In [15]:
#find the number of empty values in each column
#26 in mass and 1 in heigh
people.isnull().sum()

name              0
height            1
mass             26
hair_color        0
skin_color        0
eye_color         0
birth_year        0
gender            0
homeworld         0
films             0
species           0
vehicles          0
starships         0
url               0
film_num          0
vehicles_num      0
starships_num     0
dtype: int64

In [16]:
#find all kindes of skin
people['skin_color'].unique()

array(['fair', 'gold', 'white, blue', 'white', 'light', 'white, red',
       'unknown', 'green', 'green-tan, brown', 'pale', 'metal', 'dark',
       'brown mottle', 'brown', 'grey', 'mottled green', 'orange',
       'blue, grey', 'grey, red', 'red', 'blue', 'grey, blue',
       'grey, green, yellow', 'yellow', 'tan', 'fair, green, yellow',
       'silver, red', 'green, grey', 'red, blue, white', 'brown, white'],
      dtype=object)

In [17]:
#replace the missing values to np.nan to make it more understandable
missing_values=['??','na','X','999999']
people=people.replace(missing_values,np.NaN)
people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,url,film_num,vehicles_num,starships_num
0,Luke Skywalker,172.0,77.0,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],"[https://swapi.dev/api/vehicles/14/, https://s...","[https://swapi.dev/api/starships/12/, https://...",https://swapi.dev/api/people/1/,4,2,2
1,C-3PO,167.0,75.0,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],https://swapi.dev/api/people/2/,6,0,0
2,R2-D2,96.0,32.0,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],https://swapi.dev/api/people/3/,6,0,0
3,Darth Vader,202.0,136.0,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[https://swapi.dev/api/starships/13/],https://swapi.dev/api/people/4/,4,0,1
4,Leia Organa,150.0,49.0,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/30/],[],https://swapi.dev/api/people/5/,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Grievous,216.0,159.0,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/36/],[https://swapi.dev/api/vehicles/60/],[https://swapi.dev/api/starships/74/],https://swapi.dev/api/people/79/,1,1,1
78,Tarfful,234.0,136.0,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/3/],[],[],https://swapi.dev/api/people/80/,1,0,0
79,Raymus Antilles,188.0,79.0,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[],[],https://swapi.dev/api/people/81/,2,0,0
80,Sly Moore,178.0,48.0,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,"[https://swapi.dev/api/films/5/, https://swapi...",[],[],[],https://swapi.dev/api/people/82/,2,0,0
81,Tion Medon,206.0,80.0,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[https://swapi.dev/api/films/6/],[https://swapi.dev/api/species/37/],[],[],https://swapi.dev/api/people/83/,1,0,0

In [18]:
#fill the empty values in mass and height columns with the mean and median values of all data
m=people["mass"].mean()
h=people["height"].median()
people["mass"].fillna(m,inplace=True)
people["height"].fillna(h,inplace=True)
people["height"]

0     172.0
1     167.0
2      96.0
3     202.0
4     150.0
      ...
77    216.0
78    234.0
79    188.0
80    178.0
81    206.0
Name: height, Length: 82, dtype: float64

In [19]:
# sort data by mass and height columns in ascending for mass...and show the first of the data
people.sort_values(by=["mass", "height"], ascending=[True, False]).head()

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,url,film_num,vehicles_num,starships_num
45,Ratts Tyerel,79.0,15.0,none,"grey, blue",unknown,unknown,male,https://swapi.dev/api/planets/38/,[https://swapi.dev/api/films/4/],[https://swapi.dev/api/species/16/],[],[],https://swapi.dev/api/people/47/,1,0,0
18,Yoda,66.0,17.0,white,green,brown,896BBY,male,https://swapi.dev/api/planets/28/,"[https://swapi.dev/api/films/2/, https://swapi...",[https://swapi.dev/api/species/6/],[],[],https://swapi.dev/api/people/20/,5,0,0
28,Wicket Systri Warrick,88.0,20.0,brown,brown,brown,8BBY,male,https://swapi.dev/api/planets/7/,[https://swapi.dev/api/films/3/],[https://swapi.dev/api/species/9/],[],[],https://swapi.dev/api/people/30/,1,0,0
7,R5-D4,97.0,32.0,n/a,"white, red",red,unknown,n/a,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/films/1/],[https://swapi.dev/api/species/2/],[],[],https://swapi.dev/api/people/8/,1,0,0
2,R2-D2,96.0,32.0,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,"[https://swapi.dev/api/films/1/, https://swapi...",[https://swapi.dev/api/species/2/],[],[],https://swapi.dev/api/people/3/,6,0,0

In [20]:
#find the male people with brown skin color
people[(people["gender"] == 'male') & (people["skin_color"] == "brown")]['name']

28    Wicket Systri Warrick
52                Eeth Koth
69          Dexter Jettster
78                  Tarfful
Name: name, dtype: object

In [21]:
top_home_world_people = people[people['homeworld']=='https://swapi.dev/api/planets/20/']
top_home_world_people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,films,species,vehicles,starships,url,film_num,vehicles_num,starships_num
9,Obi-Wan Kenobi,182.0,77.0,"auburn, white",fair,blue-gray,57BBY,male,https://swapi.dev/api/planets/20/,"[https://swapi.dev/api/films/1/, https://swapi...",[],[https://swapi.dev/api/vehicles/38/],"[https://swapi.dev/api/starships/48/, https://...",https://swapi.dev/api/people/10/,6,1,5

PLANETS

In [22]:
planets = requests.get('http://swapi.dev/api/planets')

planets.json()

{'count': 60,
 'next': 'https://swapi.dev/api/planets/?page=2',
 'previous': None,
 'results': [{'name': 'Tatooine',
   'rotation_period': '23',
   'orbital_period': '304',
   'diameter': '10465',
   'climate': 'arid',
   'gravity': '1 standard',
   'terrain': 'desert',
   'surface_water': '1',
   'population': '200000',
   'residents': ['https://swapi.dev/api/people/1/',
    'https://swapi.dev/api/people/2/',
    'https://swapi.dev/api/people/4/',
    'https://swapi.dev/api/people/6/',
    'https://swapi.dev/api/people/7/',
    'https://swapi.dev/api/people/8/',
    'https://swapi.dev/api/people/9/',
    'https://swapi.dev/api/people/11/',
    'https://swapi.dev/api/people/43/',
    'https://swapi.dev/api/people/62/'],
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'created': '2014-12-09T13:50:49.641000Z',
   'edited': '2014-12-20T20:58:18.411000Z',
   'url': 'https://swapi.dev/api/planets/1/'},
  {'name': 'Alderaan',
   'rotation_period': '24',
   'orbital_period': '364',
   'diameter': '12500',
   'climate': 'temperate',
   'gravity': '1 standard',
   'terrain': 'grasslands, mountains',
   'surface_water': '40',
   'population': '2000000000',
   'residents': ['https://swapi.dev/api/people/5/',
    'https://swapi.dev/api/people/68/',
    'https://swapi.dev/api/people/81/'],
   'films': ['https://swapi.dev/api/films/1/',
    'https://swapi.dev/api/films/6/'],
   'created': '2014-12-10T11:35:48.479000Z',
   'edited': '2014-12-20T20:58:18.420000Z',
   'url': 'https://swapi.dev/api/planets/2/'},
  {'name': 'Yavin IV',
   'rotation_period': '24',
   'orbital_period': '4818',
   'diameter': '10200',
   'climate': 'temperate, tropical',
   'gravity': '1 standard',
   'terrain': 'jungle, rainforests',
   'surface_water': '8',
   'population': '1000',
   'residents': [],
   'films': ['https://swapi.dev/api/films/1/'],
   'created': '2014-12-10T11:37:19.144000Z',
   'edited': '2014-12-20T20:58:18.421000Z',
   'url': 'https://swapi.dev/api/planets/3/'},
  {'name': 'Hoth',
   'rotation_period': '23',
   'orbital_period': '549',
   'diameter': '7200',
   'climate': 'frozen',
   'gravity': '1.1 standard',
   'terrain': 'tundra, ice caves, mountain ranges',
   'surface_water': '100',
   'population': 'unknown',
   'residents': [],
   'films': ['https://swapi.dev/api/films/2/'],
   'created': '2014-12-10T11:39:13.934000Z',
   'edited': '2014-12-20T20:58:18.423000Z',
   'url': 'https://swapi.dev/api/planets/4/'},
  {'name': 'Dagobah',
   'rotation_period': '23',
   'orbital_period': '341',
   'diameter': '8900',
   'climate': 'murky',
   'gravity': 'N/A',
   'terrain': 'swamp, jungles',
   'surface_water': '8',
   'population': 'unknown',
   'residents': [],
   'films': ['https://swapi.dev/api/films/2/',
    'https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/6/'],
   'created': '2014-12-10T11:42:22.590000Z',
   'edited': '2014-12-20T20:58:18.425000Z',
   'url': 'https://swapi.dev/api/planets/5/'},
  {'name': 'Bespin',
   'rotation_period': '12',
   'orbital_period': '5110',
   'diameter': '118000',
   'climate': 'temperate',
   'gravity': '1.5 (surface), 1 standard (Cloud City)',
   'terrain': 'gas giant',
   'surface_water': '0',
   'population': '6000000',
   'residents': ['https://swapi.dev/api/people/26/'],
   'films': ['https://swapi.dev/api/films/2/'],
   'created': '2014-12-10T11:43:55.240000Z',
   'edited': '2014-12-20T20:58:18.427000Z',
   'url': 'https://swapi.dev/api/planets/6/'},
  {'name': 'Endor',
   'rotation_period': '18',
   'orbital_period': '402',
   'diameter': '4900',
   'climate': 'temperate',
   'gravity': '0.85 standard',
   'terrain': 'forests, mountains, lakes',
   'surface_water': '8',
   'population': '30000000',
   'residents': ['https://swapi.dev/api/people/30/'],
   'films': ['https://swapi.dev/api/films/3/'],
   'created': '2014-12-10T11:50:29.349000Z',
   'edited': '2014-12-20T20:58:18.429000Z',
   'url': 'https://swapi.dev/api/planets/7/'},
  {'name': 'Naboo',
   'rotation_period': '26',
   'orbital_period': '312',
   'diameter': '12120',
   'climate': 'temperate',
   'gravity': '1 standard',
   'terrain': 'grassy hills, swamps, forests, mountains',
   'surface_water': '12',
   'population': '4500000000',
   'residents': ['https://swapi.dev/api/people/3/',
    'https://swapi.dev/api/people/21/',
    'https://swapi.dev/api/people/35/',
    'https://swapi.dev/api/people/36/',
    'https://swapi.dev/api/people/37/',
    'https://swapi.dev/api/people/38/',
    'https://swapi.dev/api/people/39/',
    'https://swapi.dev/api/people/42/',
    'https://swapi.dev/api/people/60/',
    'https://swapi.dev/api/people/61/',
    'https://swapi.dev/api/people/66/'],
   'films': ['https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'created': '2014-12-10T11:52:31.066000Z',
   'edited': '2014-12-20T20:58:18.430000Z',
   'url': 'https://swapi.dev/api/planets/8/'},
  {'name': 'Coruscant',
   'rotation_period': '24',
   'orbital_period': '368',
   'diameter': '12240',
   'climate': 'temperate',
   'gravity': '1 standard',
   'terrain': 'cityscape, mountains',
   'surface_water': 'unknown',
   'population': '1000000000000',
   'residents': ['https://swapi.dev/api/people/34/',
    'https://swapi.dev/api/people/55/',
    'https://swapi.dev/api/people/74/'],
   'films': ['https://swapi.dev/api/films/3/',
    'https://swapi.dev/api/films/4/',
    'https://swapi.dev/api/films/5/',
    'https://swapi.dev/api/films/6/'],
   'created': '2014-12-10T11:54:13.921000Z',
   'edited': '2014-12-20T20:58:18.432000Z',
   'url': 'https://swapi.dev/api/planets/9/'},
  {'name': 'Kamino',
   'rotation_period': '27',
   'orbital_period': '463',
   'diameter': '19720',
   'climate': 'temperate',
   'gravity': '1 standard',
   'terrain': 'ocean',
   'surface_water': '100',
   'population': '1000000000',
   'residents': ['https://swapi.dev/api/people/22/',
    'https://swapi.dev/api/people/72/',
    'https://swapi.dev/api/people/73/'],
   'films': ['https://swapi.dev/api/films/5/'],
   'created': '2014-12-10T12:45:06.577000Z',
   'edited': '2014-12-20T20:58:18.434000Z',
   'url': 'https://swapi.dev/api/planets/10/'}]}

In [ ]:
planets = get_full_type_data('http://swapi.dev/api/planets/')
print("Number of planets",planets.shape[0])

In [ ]:
planets.head()

In [ ]:
planets.info()

In [ ]:
#find  the planets which has temperate climate and how many surface_water for each one
planets.loc[planets.climate.str.contains('temperate'), 'surface_water']

In [ ]:
#sort plantes by population
planets.sort_values(by="population", ascending=False)

In [ ]:
#fined all climate kinds
planets['climate'].unique()

In [ ]:
#change the type og those colummns to easy calculate
planets = df_columns_to_numeric(planets,["rotation_period",'orbital_period','diameter','surface_water','population'])

planets.info()

In [ ]:
missing_values=['??','Na','X','999999','unknown']
planets=planets.replace(missing_values,np.NaN)

In [ ]:
planets.describe()

In [ ]:
planets.isnull().sum()

In [ ]:
#fill the empty values of these columns by the mean
planets["rotation_period"].fillna(planets["rotation_period"].mean(),inplace=True)
planets["orbital_period"].fillna(planets["orbital_period"].mean(),inplace=True)
planets["diameter"].fillna(planets["diameter"].mean(),inplace=True)
planets["surface_water"].fillna(planets["surface_water"].mean(),inplace=True)
planets["population"].fillna(planets["population"].mean(),inplace=True)

In [ ]:
planets.isnull().sum()

In [ ]:
sns.relplot( x=planets["diameter"], y=planets["population"])

Films

In [ ]:
films= get_full_type_data('http://swapi.dev/api/films/')
print("Number of films",films.shape[0])

In [ ]:
films.head()

In [ ]:
films.info()

In [ ]:
films.columns

In [ ]:
films.describe()

In [ ]:
films.isnull().sum()

In [ ]:
missing_values=['??','na','X','999999']
films=films.replace(missing_values,np.NaN)

Speicies

In [ ]:
species= get_full_type_data('http://swapi.dev/api/species/')
print("Number of films",species.shape[0])

Vehicles

In [ ]:
vehicles = get_full_type_data('http://swapi.dev/api/vehicles/')
print("Number of vehicles",vehicles.shape[0])

Starships

In [ ]:
starships= get_full_type_data('http://swapi.dev/api/starships/')
print("Number of starships",starships.shape[0])